//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinationDream
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContract
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<int> OfferId { get; set; }
        public Nullable<System.TimeSpan> TimeSigned { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<bool> Paid { get; set; }
        public Nullable<System.TimeSpan> PaymentTime { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<bool> Refunded { get; set; }
        public Nullable<System.TimeSpan> RefundedTime { get; set; }
        public Nullable<decimal> RefundedAmount { get; set; }
    
        public virtual tblAgent tblAgent { get; set; }
        public virtual tblCustomer tblCustomer { get; set; }
    }
}
