//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinationDream
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHotelService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHotelService()
        {
            this.tblOfferHotelServices = new HashSet<tblOfferHotelService>();
            this.tblPromoOfferHotelServices = new HashSet<tblPromoOfferHotelService>();
        }
    
        public int Id { get; set; }
        public Nullable<int> HotelId { get; set; }
        public Nullable<int> RoomTypeId { get; set; }
        public Nullable<decimal> ServicePrice { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual tblHotel tblHotel { get; set; }
        public virtual tblRoomType tblRoomType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOfferHotelService> tblOfferHotelServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPromoOfferHotelService> tblPromoOfferHotelServices { get; set; }
    }
}
