//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinationDream
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOffer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOffer()
        {
            this.tblOfferHotelServices = new HashSet<tblOfferHotelService>();
            this.tblOfferTransportServices = new HashSet<tblOfferTransportService>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
        public Nullable<System.DateTime> TimeAccepted { get; set; }
        public Nullable<bool> Accepted { get; set; }
        public Nullable<int> PromoOfferId { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual tblAgent tblAgent { get; set; }
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblPromoOffer tblPromoOffer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOfferHotelService> tblOfferHotelServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOfferTransportService> tblOfferTransportServices { get; set; }
    }
}
