//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinationDream
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPromoOfferHotelService
    {
        public int Id { get; set; }
        public Nullable<int> PromoOfferId { get; set; }
        public Nullable<int> HotelServiceId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> DiscountPer { get; set; }
        public Nullable<decimal> FinalServicePrice { get; set; }
        public string Discription { get; set; }
    
        public virtual tblHotelService tblHotelService { get; set; }
        public virtual tblPromoOffer tblPromoOffer { get; set; }
    }
}
