//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinationDream
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransportService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTransportService()
        {
            this.tblOfferTransportServices = new HashSet<tblOfferTransportService>();
            this.tblPromoOfferTransportServices = new HashSet<tblPromoOfferTransportService>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TransportCompanyId { get; set; }
        public Nullable<int> TicketTypeId { get; set; }
        public Nullable<int> FromCityId { get; set; }
        public Nullable<int> ToCityId { get; set; }
        public Nullable<decimal> ServicePrice { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual tbl_Cities tbl_Cities { get; set; }
        public virtual tbl_Cities tbl_Cities1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOfferTransportService> tblOfferTransportServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPromoOfferTransportService> tblPromoOfferTransportServices { get; set; }
        public virtual tblTicketType tblTicketType { get; set; }
        public virtual tblTransportCompany tblTransportCompany { get; set; }
    }
}
