//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinationDream
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelAgencyEntities : DbContext
    {
        public TravelAgencyEntities()
            : base("name=TravelAgencyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Cities> tbl_Cities { get; set; }
        public virtual DbSet<tblAgent> tblAgents { get; set; }
        public virtual DbSet<tblCompanyType> tblCompanyTypes { get; set; }
        public virtual DbSet<tblContract> tblContracts { get; set; }
        public virtual DbSet<tblCountry> tblCountries { get; set; }
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblHotel> tblHotels { get; set; }
        public virtual DbSet<tblHotelService> tblHotelServices { get; set; }
        public virtual DbSet<tblMenu> tblMenus { get; set; }
        public virtual DbSet<tblOffer> tblOffers { get; set; }
        public virtual DbSet<tblOfferHotelService> tblOfferHotelServices { get; set; }
        public virtual DbSet<tblOfferTransportService> tblOfferTransportServices { get; set; }
        public virtual DbSet<tblPromoOffer> tblPromoOffers { get; set; }
        public virtual DbSet<tblPromoOfferHotelService> tblPromoOfferHotelServices { get; set; }
        public virtual DbSet<tblPromoOfferTransportService> tblPromoOfferTransportServices { get; set; }
        public virtual DbSet<tblRoomType> tblRoomTypes { get; set; }
        public virtual DbSet<tblState> tblStates { get; set; }
        public virtual DbSet<tblTicketType> tblTicketTypes { get; set; }
        public virtual DbSet<tblTransportCompany> tblTransportCompanies { get; set; }
        public virtual DbSet<tblTransportService> tblTransportServices { get; set; }

        public System.Data.Entity.DbSet<DestinationDream.Models.Cities> Cities { get; set; }

        public System.Data.Entity.DbSet<DestinationDream.Models.Countries> Countries { get; set; }
    }
}
